<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Models\Guardian; use App\Models\Student; use App\Models\User; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Hash;
class GuardianController extends Controller {
 public function index(){return view('admin.guardians.index',['guardians'=>Guardian::with('user','students.user')->paginate(15)]);} public function create(){$students=Student::with('user')->get();return view('admin.guardians.create',compact('students'));}
 public function store(Request $request){$v=$request->validate(['name'=>'required|string|max:100','email'=>'required|email|unique:users,email','phone'=>'nullable|string|max:20','nik'=>'required|string|max:30|unique:parents,nik','relationship'=>'nullable|string|max:50','occupation'=>'nullable|string|max:100','address'=>'nullable|string','student_ids'=>'required|array|min:1','student_ids.*'=>'exists:students,nis']);DB::transaction(function()use($v){Guardian::create(['nik'=>$v['nik'],'relationship'=>$v['relationship']??null,'occupation'=>$v['occupation']??null,'address'=>$v['address']??null]);$g=Guardian::find($v['nik']);User::create(['name'=>$v['name'],'email'=>$v['email'],'phone'=>$v['phone']??null,'password'=>Hash::make('password123'),'role'=>'orangtua','academic_key'=>$v['nik']]);$g->students()->sync($v['student_ids']);});return redirect()->route('admin.guardians.index')->with('success','Orang tua berhasil ditambahkan. Password default: password123');}
 public function edit(Guardian $guardian){$guardian->load('user','students');$students=Student::with('user')->get();return view('admin.guardians.edit',compact('guardian','students'));}
 public function update(Request $request,Guardian $guardian){$v=$request->validate(['name'=>'required|string|max:100','email'=>'required|email|unique:users,email,'.$guardian->user?->id,'phone'=>'nullable|string|max:20','nik'=>'required|string|max:30|unique:parents,nik,'.$guardian->nik.',nik','relationship'=>'nullable|string|max:50','occupation'=>'nullable|string|max:100','address'=>'nullable|string','student_ids'=>'required|array|min:1','student_ids.*'=>'exists:students,nis']);DB::transaction(function()use($v,$guardian){$guardian->update(['nik'=>$v['nik'],'relationship'=>$v['relationship']??null,'occupation'=>$v['occupation']??null,'address'=>$v['address']??null]);$guardian->user()->update(['name'=>$v['name'],'email'=>$v['email'],'phone'=>$v['phone']??null,'academic_key'=>$v['nik']]);$guardian->students()->sync($v['student_ids']);});return redirect()->route('admin.guardians.index')->with('success','Data orang tua berhasil diperbarui.');}
 public function destroy(Guardian $guardian){$guardian->user()?->delete();$guardian->delete();return redirect()->route('admin.guardians.index')->with('success','Orang tua berhasil dihapus.');}
}
